CREATE SCHEMA IF NOT EXISTS booking;

SET SCHEMA booking;

CREATE TABLE IF NOT EXISTS UserData (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL

);

CREATE TABLE IF NOT EXISTS Seat(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    seatNumber INTEGER NOT NULL,
    sectionType VARCHAR(5) NOT NULL,
    available BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS Ticket (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    userId BIGINT NOT NULL,
    source VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    paymentMode VARCHAR(255) NOT NULL,
    sectionType VARCHAR(255) NOT NULL,
    numberOfTicket SMALLINT NOT NULL,
    allocatedSeats VARCHAR(255) NOT NULL,
    isActive BOOLEAN NOT NULL

);
